# =========================
# PERFIL PRODUCCION (main o dev)
# Puerto: 8443 HTTPS
# =========================

server.port=8443

# SSL
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore-prod.jks
server.ssl.key-store-password=secretprod
server.ssl.key-store-type=JKS
server.ssl.key-alias=mokafprod

# Logging mínimo
logging.level.root=WARN
spring.jpa.show-sql=false